---
- name: Install IIS
  hosts: win
  gather_facts: true
  tasks:
   - name: Install IIS
     win_feature:
       name: "Web-Server"
       state: present
       restart: no
       include_sub_features: no 
       include_management_tools: yes  
   
   - name: Reboot
     win_reboot:
