---
    # inside vmware servers contained in folders, servers named after agency, broken down by datacenter SDC/ADC. 
      # --> Arjun to login to vcenter
      # vcenter might need to be a variable to see where server is and pipe into this pb

- name: Add an additional cpu to virtual machine server
  hosts: '{{ target }}' 
  
  tasks: 
    - name: Login into vCenter and get cookies
      vmware_guest: 
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        folder: "{{ vm_folder }}"   
        cluster: "{{ vcenter_cluster }}"
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ vm_name }}"
    - name:
      uri:
        url: https://{{ vcenter_hostname }} #/rest/com/vmware/cis/session
        force_basic_auth: yes
        validate_certs: yes
        method: POST
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        folder: "{{ vm_folder }}"   
        cluster: "{{ vcenter_cluster }}"
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ vm_name }}"
      #register: login

  #- name: Get all hosts from vCenter using cookies from last task
   # uri:
    #  url: https://{{ vcenter_server }} #/rest/vcenter/host
     # force_basic_auth: yes
      #validate_certs: no
      #headers:
      #Cookie: "{{ login.set_cookie }}"
    #register: vchosts
  
    - name: Stop virtual machine
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "false"
        folder: "{{ vm_folder }}"   
        cluster: "{{ vcenter_cluster }}"
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ vm_name }}"
        state: "poweredoff"
      #delegate_to: "localhost"
      #register: stop_vm

    - name: reconfigure CPU and RAM of VM
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster: "{{ vcenter_cluster }}"
        datacenter: "{{ vcenter_datacenter }}"
        name: "{{ vm_name }}"
      #state: "poweredon"
        state: "present"
      #state: "poweredoff"
        validate_certs: "false"
        folder: "{{ vm_folder }}"
        hardware:
          memory_gb: "{{ memory }}"
          num_cpus: "{{ cpu }}"
        scsi: "lsilogic"
      #delegate_to: "localhost"
