---
- hosts: all
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  vars:
    ansible_python_interpreter: /bin/python3

# Pre-requisites note: 
# On golden images for rhel7/rhel8, 
# yum install python2-pip and yum install python3-pip to use ansible pip module.  Did this for future proofing. 
# No need to use makepasswd package or expect package via yum. Passwd automatically hashes password and adds to /etc/shadow.
  
  tasks:
  
 # Required to use the expect module
   - name: Install pexpect through pip
     become: true
     pip:
       name: "pexpect>=3.3"
       state: present
  
   - name: Add group "sotaadmin" to remote server
     group:
       name: sotaadmin
       gid: 38000
       state: present

   # NOTE: created this var first to make it lowercase b/c doing so afterwards was not loggically working. 
   - name: create var that is lowercase coming from the passed "agency" var from VRA
     set_fact: 
       lower_agency: "{{ agency | lower}}"

   - name: Create local agency user to remote server
     user:
       name: "{{ lower_agency }}user"
       update_password: always
       state: present
       comment:  897/C/{{ lower_agency }}user/Agency Admin 
       uid: 38001
       group: sotaadmin
       append: yes
       shell: /bin/bash
       createhome: yes
     register: agencyUser

   - name: Set password for user
     expect:
       command: passwd "{{ lower_agency }}user"
       responses:
         (?i)password: "MySekretPa$$word"  
 
   - name: Force user to change password
     shell: chage -d 0 {{ lower_agency }}user
