---
- name: Get vm datastore info
  hosts: localhost
  gather_facts: false
  vars: 
    - ansible_python_interpreter: "/usr/bin/python3"
  vars_files: 
    - /home/uipath01/vars/vault.yml
    - /home/uipath01/vars/main.yml

  tasks: 
    - set_fact:
        vm_name: "{{ target_name }}"

    - name: "Find folder for VM - {{ vm_name }}"
      vmware_guest_find: 
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        name: "{{ vm_name }}"
      register: vm_facts 
      delegate_to: localhost
      
    - name: Gather info from standalone ESXi server having datacenter as 'X datacenter' # pass datacenter in your command as variable.
      vmware_datastore_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter_name: '{{ dc }}'
        validate_certs: no
      delegate_to: localhost
      register: datacenter_info