--- 
- hosts: linux 

  become: yes 

  become_user: root 

  #remote_user: mbrady 
  
  become_method: sudo 
 
  tasks: 
  
  - name: Rebooting the host atinmslx02 
  
    command: /sbin/shutdown -r now 
