---
- name: get folder path and modify memory of vm
  hosts: localhost
  gather_facts: false
  vars: 
    ansible_python_interpreter: "/usr/bin/python3"

  tasks: 
    - set_fact: #set variable
        vm_name: "{{ target_name }}"
        change_memory: "{{ memory }}"

    - name: "Find folder for VM - {{ vm_name }}"
      vmware_guest_find: 
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        name: "{{ vm_name }}"
      register: vm_facts
      delegate_to: localhost

    - name: Stop virtual machine
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        folder: "{{ vm_facts }}"   
        name: "{{ vm_name }}"
        state: "poweredoff"
      register: stop_vm
      delegate_to: "localhost"
      

    - name: modify memory
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}" 
        validate_certs: no
        folder: '{{ vm_facts }}'
        name: "{{ vm_name }}"
        state: "present"
        hardware: 
          memory_mb: "{{ memory }}"
          scsi: paravirtual
      register: modify_memory
      delegate_to: "localhost"
      
    
    - name: Power on virtual machine
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}" 
        validate_certs: no
        folder: '{{ vm_facts }}'
        name: "{{ vm_name }}"
        state: "poweredon"
        hardware: 
          memory_mb: "{{ memory }}"
          scsi: paravirtual
      register: start_vm
      delegate_to: "localhost"

        
        
  
