# Purpose: Replace ALL of the 3 different scenarios of inccorect text written to the /etc/issue, /etc/issue.net, and /etc/motd as well as fixing /etc/hosts and the /etc/sysconfig/network-scripts/ifcfg-ens192 configuration. 
# Note: The copy module worked best here because it overwrites the file outright with the content you want. It doesn't care what text was in the file originally. This solved the scenario of having 3 differents sets of text in 3 different files. 

- name: Replace text 
  hosts: all
  gather_facts: no

  tasks: 

  - name: replace the text of the file
    copy:
      content: "{{ agency }}'s systems must only be used for conducting {{ agency }}'s business or for purposes authorized by management."
      dest: /etc/issue

  - name: replace the text of the file
    copy:
      content: "{{ agency }}'s systems must only be used for conducting {{ agency }}'s business or for purposes authorized by management."
      dest: /etc/issue.net

  - name: replace the text of the file
    copy:
      content: "{{ agency }}'s systems must only be used for conducting {{ agency }}'s business or for purposes authorized by management."
      dest: /etc/motd
    
  - name: replace the text TXDCS with the agency acronynm
    replace: 
      path: /etc/hosts
      regexp: EXAMPLE1.TX.GOV
      replace: "{{ domain }}" 

  - name: replace the text Peer_DNS=yes to Peer_DNS=no
    replace: 
      path: /etc/sysconfig/network-scripts/ifcfg-ens192
      regexp: '^PEERDNS=yes'
      replace: 'PEERDNS=no' 
  
  - name: delete Domain= line if found in /etc/sysconfig/network-scripts/ifcfg-ens192
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-ens192
      regexp: '^DOMAIN='
      state: absent

  - name: delete DNS1 line if found in /etc/sysconfig/network-scripts/ifcfg-ens192
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-ens192
      regexp: '^DNS1='
      state: absent

  - name: delete DNS2= line if found in /etc/sysconfig/network-scripts/ifcfg-ens192
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-ens192
      regexp: '^DNS2='
      state: absent

  - name: delete DNS3= line if found in /etc/sysconfig/network-scripts/ifcfg-ens192
    lineinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-ens192
      regexp: '^DNS3='
      state: absent
