---
- name: Linux snmpd steps
  hosts: '{{ target }}' 
  become: yes
  become_method: sudo
  gather_facts: no

  tasks: 
 
  - name: Status before stopped
    command: service snmpd status
     
  - name: Stop the service
    service: name='{{ service_name }}' state=stopped  

  - name: Enable the service
    service: name='{{ service_name }}' enabled=yes

  - name: Start the service
    service: name='{{ service_name }}' state=started
 
  - name: Status after started
    #shell: service snmpd status
    command: service snmpd status
