---
- name: Bigfix playbook
  hosts: '{{ target }}' 
  become: yes
  gather_facts: no

  tasks:    
  
  - name: Status before stop 
    command: service besclient status

  - name: Stop besclient
    command: service besclient stop

  - name: Enable besclient
    service: name=besclient enabled=yes

  - name: Start besclient
    command: service besclient start

  - name: Status after start 
    command: service besclient status 