---
- name: Avamar playbook
  hosts: '{{ target }}'
  become: yes
  gather_facts: no

  tasks:
  - name: Status before stop
    command: service avagent status

  - name: Start avamar
    service: name= '{{ service_name }}' state=restarted

  - name: Status after start
    command: service avagent status
