---
- name: Avamar playbook
  hosts: '{{ target }}'
  become: yes
  gather_facts: no

  tasks:
  - name: Status before stop
    command: service avagent status

  - name: Start avamar
    service: name= '{{ service_name }}' state=restarted
    # note: service doesn't give you any stdout and stderror. I needed that to provide to developers. Use command module instead. 

  - name: Status after start
    command: service avagent status
