---
- name: Reboot a host and wait for it to return
  hosts: linux 
  remote_user: mbrady
  tasks:
     #Send the reboot command
    - shell: sleep 5 && sudo shutdown now -r 

    # This pause is mandatory, otherwise the existing control connection gets reused!
    - pause: minutes=1

     #Now we will run a local 'ansible -m ping' on this host until it returns.
     #This works with the existing ansible hosts inventory and so any custom ansible_ssh_hosts definitions are being used
    - local_action: shell ansible -u {{ ansible_user }} -m ping {{ linux }}
      register: results
      until: result.rc == 0
      retries: 30
      delay: 10

     # And finally, execute 'uptime' when the host is back.
    - shell: uptime
