---
- hosts: linux
  tasks:
  - name: Restart machine
    #msg: "Reboot initiated by Ansible"
    shell: "sleep 5 && sudo shutdown -r now"
    async: 1
    poll: 0

  - name: Wait for server to restart 
    local_action:  
     module: wait_for
      host={{ ansible_host }} state=started
      port=22
      delay=30
      connect_timeout=15
      timeout=300
  # I can delay up time after "X" amount of minutes as a test too. 
  - shell: sleep 30 && uptime
  # Run ping command to make sure host is online after 3 minutes. Eric asked for 10. 
  #- shell: sleep 15 && ping {{ hosts }} 
